INSERT INTO roles (nombre)
VALUES ('USUARIO')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO roles (nombre)
VALUES ('TRABAJADOR')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO roles (nombre)
VALUES ('ENTRENADOR')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO roles (nombre)
VALUES ('ADMINISTRADOR')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

INSERT INTO roles (nombre)
VALUES ('SOPORTE_TECNICO')
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);
