spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/club_deportivo
    username: root
    password: gokussj5202

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG

app:
  jwt:
    secret: cambia-este-secreto-en-produccion-con-minimo-32-caracteres
    expiration-minutes: 120
